version: '3.8'
services:
  appseed-app:
    container_name: appseed_app
    command: python manage.py runserver 0.0.0.0:8000
    restart: always
    env_file: .env
    build: .
    networks:
      - db_network
      - web_network
    ports:
      - "80:8000"
networks:
  db_network:
    driver: bridge
  web_network:
    driver: bridge
 